
data_path: "data/Clean_Dataset.csv"
model_path : "artifacts/model.pkl"
scaler_path: "artifacts/scaled.pkl"
encoder_path : "artifacts/encoders.pkl"
feature_path : "artifacts/features.json"


target_column: "price"

features:
  - airline
  - source_city
  - departure_time
  - stops
  - destination_city
  - class
  - days_left

